spring:
  jpa:
    database: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/example?useSSL=false&serverTimezone=UTC
    username: root
    password: 2020.ut
    driverClassName: com.mysql.cj.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1