spring:
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    ## default connection pool
    hikari:
      connectionTimeout:20000
      maximumPoolSize=5
  datasource:
    url: jdbc:mysql://localhost:3306/example?useSSL=false&serverTimezone=UTC
    username: root
    password: 2020.ut
    driverClassName: com.mysql.cj.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1

server:
  port: 8080